### ISSUE TITLE
iscsid need to restart 

### ISSUE THREAD

**Issue by zhangleimao** [lolwww/charm-cinder-oceanstor#11]
What I deploy this charm along with cinder which runs on dedicated ceph nodes, I need to run "systemctl restart iscsid" to make server create boot from volume working.

**Comment by nobuto-m** [comment]
https://bugs.launchpad.net/charm-cinder/+bug/1825809

**Comment by nobuto-m** [comment]
As per above. We will treat it as a charm-cinder issue instead for now.
